### ISSUE TITLE
How to useEffect 

### ISSUE THREAD

**Issue by eggei** [yilmaz1998/AI-translator#1]
`useEffect`'i daha iyi anlaman ve kullanman cok isine yarayacak.

Once burayi bir oku. Satir bile atlamadan, dikkatini vererek oku. - https://react.dev/reference/react/useEffect
Ardindan, bu videoyu normal hizinda ve atlamadan dinle: https://www.youtube.com/watch?v=bGzanfKVFeU

Son olarak da, 
1. Bu `useEffect` icin nasil duzeltmeler yapabilecegini bul. React gelistiricilerinin en zayif tarafi `useEffect` i tam anlamamalari ve biriken basit hatalardan oturu kotu bir aplikasyona sebep olmalari.
2. `fetch` yerine nasil bir fetching alternatifi kullanabilecegini dusun ve uygula (yukarda paylastigim react'in kendi documantasyonunda buna dair tavsiyede bulunuyor.

https://github.com/yilmaz1998/AI-translator/blob/a49ad6993052a13c6d50d9a881adcc475fe1f85f/translator/app/english-translation/page.js#L14-L49

**Comment by eggei** [comment]
Goruyorum ki Axios kullanmaya karar vermissin. Ancak, Axios sadece bir fetch replacement'i. React dokumaninda soyle bir bolum bulacaksin: https://react.dev/reference/react/useEffect#what-are-good-alternatives-to-data-fetching-in-effects
Bu, yeni tarz data fetching/caching ve state management artik cok populer ve cok daha efektif. Benim favorim, `useSWR`. `react-query` 'de mukemmel bir alternatif. Bunlara bakmani ve uygulamani oneririm.

**Comment by yilmaz1998** [comment]
Çok teşekkür ediyorum. useSWR’yi uygulayacağım fetch için en kısa sürede. Araştırdım videolar da izledim onun hakkında. Verdiğiniz bilgiler çok önemli çok sağolun ilgilendiğiniz için. Kendimi geliştirmeme yardımcı oluyorsunuz.

**Comment by eggei** [comment]
Onemli degil :) 

Degisimler yaptiginda lutfen PR ac ve benden review request et. Boylece cok daha efektif bicimde tartisiriz. Ayrica bu Issue'lari onlara baglariz. PR'lari merge ettiginde Issue'lar da kapanir.
