### ISSUE TITLE
DRY

### ISSUE THREAD

**Issue by eggei** [yilmaz1998/AI-translator#2]
Burayi nasil [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) yapabiliriz?

https://github.com/yilmaz1998/AI-translator/blob/a49ad6993052a13c6d50d9a881adcc475fe1f85f/translator/app/english-translation/page.js#L65-L79

**Comment by yilmaz1998** [comment]
English ifadelerini kaldirdim. User switch edebiliyor.

**Comment by eggei** [comment]
Sinancim, Pull Request ac bir dahaki degisimlerinde, boylelikle onun uzerinde tartisabiliriz.

**Comment by eggei** [comment]
DRY yalnizca ayni kelimeleri tekrar etmemek degil ayni zamanda repetitive code'u basite indirgemekle alakali. Burada yapabilecegin ve React kodunda cok yaygin kullanilan birsey var.

```js
const toEnglishOptions = [
  { label: 'Spanish', enToOther: 'es-en', otherToEn: 'es-en' }, 
  { label: 'Turkish', enToOther: 'tr-en', otherToEn: 'tr-en' },
  // ...others
]

// in the rendering part:
return (
  <select ...>
    {options.map(o => (
      <option value={option[mode]}>{option.label}</option>
    ))}
  </select>
)
```

Dikkat: Bunun calismasi icin `mode`'un degerlerini degistrimen lazim. `enToOther` ve `otherToEn` olmasi lazim. Aslen, su anki degerlerini de kullana bilirsin ama o zaman option objelerinin key'leri garip olacak. Sunun gibi:
```js
const options = [{ label: "Spanish", "en-to-other": "en-es", "other-to-en": "es-en" }}]
```
