### ISSUE TITLE
DRY-2

### ISSUE THREAD

**Issue by eggei** [yilmaz1998/AI-translator#3]
#2 'yi okumadan buna baslama

Bu iki dosya nerdeyse birbirinin aynisi, bunlarin componentlerini nasil abstract hale getirebilirsin ve gereksiz yere tekrarlar yapmazsin? 

- https://github.com/yilmaz1998/AI-translator/blob/main/translator/app/english-translation/page.js
- https://github.com/yilmaz1998/AI-translator/blob/main/translator/app/translation-to-english/page.js

Tip: Tek bir file olsa, `translator-page.js` mesela, ve o bazi componentler import etse. Nerede ve nasil kullanildigina gore degisik sonuclar veren komponentler...

**Comment by yilmaz1998** [comment]
Componentleri tek bir yerde birlestirip dynamic hale getirdim. Ayrica, API call esnasinda timeout ekledim boylece direkt hata vermiyor 3 defa 10'ar saniye verip kendi kendine tekrardan new request olusturuyor. https://ai-translator-pi.vercel.app/

**Comment by eggei** [comment]
Sinan, bir problem var. Turkce'den Ingilizce'ye ceviri yapmaya calistim ve bu error verdi.

<img width="1476" alt="Screenshot 2024-12-04 at 10 20 27 AM" src="https://github.com/user-attachments/assets/ed57975d-88d9-4e15-b0f7-bdb9bf8c40dc">

**Comment by eggei** [comment]
Bu arada, otomatik olarak request gonderdigi hali cok guzeldi. Bence ona geri don ve sana onerdigim gibi debounce kullan. Debounce icin `lodash/debounce` 'u yukleyebilirsin NPM'den: https://lodash.com/docs/4.17.15#debounce (npm: https://www.npmjs.com/package/lodash.debounce)

Nasil isledigini anlamak icin de buraya bakabilirsin: 
- https://www.geeksforgeeks.org/debouncing-in-javascript/
- https://www.geeksforgeeks.org/lodash-_-debounce-method/

**Comment by yilmaz1998** [comment]
Local’da çalıştırdığım zaman bi sorun olmuyor. Ama deployed halini çalıştırınca zaman aşımına giriyor ve hata veriyor eğer request uzun sürünce. Vercelde 10 saniyeyi geçince hata veriyor.

**Comment by eggei** [comment]
Bu while loop'a tekrar bak. Dogru olmamis. 
https://github.com/yilmaz1998/AI-translator/blob/f752cbd7751c674241d1b404480565bc4f4e999f/translator/pages/api/huggingface/index.js#L53-L72

**Comment by eggei** [comment]
Tip: Yalnizca basarisiz request'in retry yapmasi lazim. Sen daha en bastan 3 request atiyorsun.

**Comment by yilmaz1998** [comment]
Çok teşekkürler. En kısa sürede düzelteceğim.

**Comment by eggei** [comment]
Diger Issue'daki yorum gibi. Lutfen PR ac.

**Comment by yilmaz1998** [comment]
Anladım. PR yapmam için başka branch açıp ordan değişikleri yapmam gerekiyor değil mi?

**Comment by eggei** [comment]
Evet
1. New branch: `git checkout -b sinan/<insert-your-feature-name>`
After changes: 
2. `git add .`
3. `git commit -m "this change that change"`
4. `git push origin sinan/<insert-your-feature-name>`
5. Then go on GitHub and open a new PR against the `main` branch.
6. Request my review from top left in PR view.
